export const episodes = [
    {
        "season_number": 1,
        "title": "Uno",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Mijo",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Nacho",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Hero",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Alpine Shepherd Boy",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Five-O",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Bingo",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "RICO",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Pimento",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 1,
        "title": "Marco",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Switch",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Cobbler",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Amarillo",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Gloves Off",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Rebecca",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Bali Ha'i",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Inflatable",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Fifi",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Nailed",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 2,
        "title": "Klick",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Mabel",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Witness",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Sunk Costs",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Sabrosito",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Chicanery",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Off Brand",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Expenses",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Slip",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Fall",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 3,
        "title": "Lantern",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Smoke",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Breathe",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Something Beautiful",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Talk",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Quite a Ride",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Piñata",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Something Stupid",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Coushatta",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Wiedersehen",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 4,
        "title": "Winner",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Magic Man",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "50% Off",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "The Guy For This",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Namaste",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Dedicado a Max",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Wexler v. Goodman",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "JMM",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Bagman",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Bad Choice Road",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 5,
        "title": "Something Unforgivable",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Wine and Roses",
        _id: '1',
        episode_number: 1,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Carrot and Stick",
        _id: '1',
        episode_number: 2,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Rock and Hard Place",
        _id: '1',
        episode_number: 3,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Black and Blue",
        _id: '1',
        episode_number: 4,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Axe and Grind",
        _id: '1',
        episode_number: 5,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Plan and Execution",
        _id: '1',
        episode_number: 6,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Point and Shoot",
        _id: '1',
        episode_number: 7,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Fun and Games",
        _id: '1',
        episode_number: 8,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Nippy",
        _id: '1',
        episode_number: 9,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Breaking Bad",
        _id: '1',
        episode_number: 10,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Waterworks",
        _id: '1',
        episode_number: 11,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    },
    {
        "season_number": 6,
        "title": "Saul Gone",
        _id: '1',
        episode_number: 12,
        thumbnail: 'https://www.hollywoodreporter.com/wp-content/uploads/2022/04/Better-Call-Saul-S6-Still-Jimmy-McGill-Publicity-H-2022.jpg?w=1296',
        src:'https://d34lypc6o619vf.cloudfront.net/bcs%205-1.mp4',
    }
]

