//this data is used in populate.js to populate MongoDB
module.exports.episodes = [
    {
        "season_number": 1,
        "description": 'Jimmy McGill, a struggling lawyer, tries to make a name for himself in the legal world, while dealing with personal and financial challenges.',
        "title": "Uno",
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy's business relationship with the Kettlemans takes a dangerous turn, while he tries to negotiate a deal with Nacho, a local criminal.",
        "title": "Mijo",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy's moral dilemma grows as he tries to help Nacho steal drugs from the Kettlemans, while Mike Ehrmantraut gets involved in a deal gone wrong.",
        "title": "Nacho",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy's publicity stunt for his law practice turns out to be more than he bargained for, while Chuck struggles with his electromagnetic hypersensitivity.",
        "title": "Hero",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy helps a client avoid jail time, while Mike's past catches up with him, forcing him to make a tough decision.",
        "title": "Alpine Shepherd Boy",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Mike's backstory is revealed as he deals with the aftermath of his son's death, while Jimmy tries to help him get justice.",
        "title": "Five-O",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy finds himself in trouble with the law after a scam goes wrong, while Chuck tries to prove that Jimmy is not fit to practice law.",
        "title": "Bingo",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy and Kim team up to take down a corporate law firm, while Mike deals with the consequences of his actions.",
        "title": "RICO",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy's relationship with Kim takes a turn, while he faces the consequences of his past actions and struggles with his conscience.",
        "title": "Pimento",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 1,
        "description": "Jimmy's old friend Marco pays him a visit, leading to a trip down memory lane and a glimpse of Jimmy's past.",
        "title": "Marco",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy considers a job offer at a law firm, while Mike starts to investigate a new criminal enterprise.",
        "title": "Switch",
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy and Kim's relationship becomes more complicated, while Mike's investigation takes a dangerous turn.",
        "title": "Cobbler",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy and Kim team up for a high-stakes case, while Mike tries to avoid being caught by the cartel.",
        "title": "Amarillo",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy takes matters into his own hands when his relationship with Kim is threatened, while Mike's past catches up with him.",
        "title": "Gloves Off",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy tries to help a client get out of a difficult situation, while Chuck struggles with his illness.",
        "title": "Rebecca",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy and Kim's relationship reaches a breaking point, while Mike takes a job to make ends meet.",
        "title": "Bali Ha'i",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy tries to cover up his tracks, while Mike's plan to take down the Salamancas backfires.",
        "title": "Inflatable",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy and Kim take on a big client, while Mike's plan to disrupt the Salamancas' drug supply goes awry.",
        "title": "Fifi",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": "Jimmy and Kim's plan to take down Chuck is put into motion, while Mike faces the consequences of his actions.",
        "title": "Nailed",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 2,
        "description": 'Jimmy and Kim deal with the fallout of their actions, while Mike makes a difficult decision.',
        "title": "Klick",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "description": "Jimmy deals with the aftermath of his confrontation with Chuck, while Kim tries to keep her career on track.",
        "title": "Mabel",
        "season_number": 3,
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy and Kim team up for a new client, while Mike continues his investigation into the Salamancas.",
        "title": "Witness",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy's actions have consequences for Kim, while Mike tries to get closer to the Salamancas.",
        "title": "Sunk Costs",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy and Kim deal with the fallout of their actions, while Gus Fring makes his presence known.",
        "title": "Sabrosito",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy and Chuck's feud comes to a head in court, while Mike deals with a problem at the Salamanca drug operation.",
        "title": "Chicanery",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy tries to get back on his feet, while Mike deals with a setback in his investigation.",
        "title": "Off Brand",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy tries to impress a potential client, while Mike continues to search for a way to disrupt the Salamancas.",
        "title": "Expenses",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy's schemes catch up with him, while Kim faces a difficult decision.",
        "title": "Slip",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy's actions have far-reaching consequences, while Mike faces a crisis of conscience.",
        "title": "Fall",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 3,
        "description": "Jimmy and Chuck's relationship reaches a breaking point, while Mike tries to make things right with his family.",
        "title": "Lantern",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy struggles to move on from Chuck's death, while Gus Fring hires a new employee.",
        "title": "Smoke",
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy and Kim take on a new client, while Nacho tries to sabotage the Salamanca drug operation.",
        "title": "Breathe",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy tries to make amends, while Gus Fring deals with a problem at the laundromat.",
        "title": "Something Beautiful",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy and Kim's relationship is tested, while Mike tries to cover his tracks.",
        "title": "Talk",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy takes a trip down memory lane, while Mike deals with a new problem at the lab.",
        "title": "Quite a Ride",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy's past catches up with him, while Gus Fring makes a move against his rivals.",
        "title": "Piñata",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy and Kim's plan to take down Howard goes awry, while Nacho faces a difficult decision.",
        "title": "Something Stupid",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy and Kim team up for a scam, while Mike's plan to disrupt the Salamanca operation hits a snag.",
        "title": "Coushatta",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy's old friend comes back into his life, while Gus Fring deals with a problem at the chicken farm.",
        "title": "Wiedersehen",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 4,
        "description": "Jimmy's actions have consequences for Kim, while Mike's plan to take down the Salamanca operation comes to fruition.",
        "title": "Winner",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim's relationship is tested, while Mike tries to cover up his tracks.",
        "title": "Magic Man",
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim take on a new client, while Mike deals with a problem at the lab.",
        "title": "50% Off",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim's scam goes wrong, while Mike tries to recruit new help for his operation.",
        "title": "The Guy For This",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim's relationship is strained, while Mike tries to find a way to get rid of Lalo.",
        "title": "Namaste",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy takes on a new identity to get out of trouble, while Nacho tries to find a way out of the Salamanca organization.",
        "title": "Dedicado a Max",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim's relationship reaches a breaking point, while Mike tries to get Lalo out of the picture.",
        "title": "Wexler v. Goodman",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy's past catches up with him, while Kim tries to make a change in her career.",
        "title": "JMM",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Mike take on a dangerous job in the desert, while Kim faces a difficult decision.",
        "title": "Bagman",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim deal with the aftermath of their actions, while Mike tries to keep a low profile.",
        "title": "Bad Choice Road",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 5,
        "description": "Jimmy and Kim's relationship is tested, while Gus Fring makes a bold move.",
        "title": "Something Unforgivable",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Nacho runs for his life. Saul and Kim hatch a plan to mess with Howard. Mike questions his allegiances. ",
        "title": "Wine and Roses",
        "episode_number": 1,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Kim and Saul enlist some familiar faces in their scheme to get Howard. Harsh realities dawn on Nacho. Gus investigates his suspicions. ",
        "title": "Carrot and Stick",
        "episode_number": 2,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Still on the run, Nacho is forced to choose where his loyalties lie. Saul must decide whether he wants to remain a \"friend of the cartel\" after his reputation is called into question. Gus and Mike ready the team for a meet. ",
        "title": "Rock and Hard Place",
        "episode_number": 3,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Despite assurances from the cartel, Gus takes extreme measures to protect himself against looming threats. Kim and Saul enlist the help of a local pro to put on a show for Cliff Main. Howard seeks outside counsel.",
        "title": "Black and Blue",
        "episode_number": 4,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "While business booms for Jimmy, the vise tightens on the cat-and-mouse game between Gus and Lalo. ",
        "title": "Axe and Grind",
        "episode_number": 5,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Jimmy and Kim deal with a last-minute snag in their plan; Lalo is forced to make an unexpected move. ",
        "title": "Plan and Execution",
        "episode_number": 6,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "An unexpected visitor forces Jimmy and Kim to face the consequences of their actions.",
        "title": "Point and Shoot",
        "episode_number": 7,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Gus attempts to smooth things over with the cartel while Mike ties up loose ends as Jimmy and Kim deal with the repercussions of their actions. ",
        "title": "Fun and Games",
        "episode_number": 8,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "A lost dog leads to a new friend. A new player gets in the game.",
        "title": "Nippy",
        "episode_number": 9,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "The partners escalate their enterprise to new levels.",
        "title": "Breaking Bad",
        "episode_number": 10,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "The stakes are raised when a discovery is made that will send shockwaves far and wide. ",
        "title": "Waterworks",
        "episode_number": 11,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    },
    {
        "season_number": 6,
        "description": "Revelations. Regrets. RICO violations. Jimmy's worlds - and identities - converge in one final showdown.",
        "title": "Saul Gone",
        "episode_number": 12,
        "src":'https://d34lypc6o619vf.cloudfront.net/bcs%205-2.mp4',
    }
]
